apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: mongo-app
spec:
  # 3 Pods should exist at all times.
  replicas: 3
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: mongo-app
    spec:
      containers:
      - name: mongo-app
        # Run this image
        image: mongo:latest

---

kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: service-mongodb
spec:
  ports:
    # Accept traffic sent to port 80
    - name: tcp
      port: 27017
      targetPort: 27017
  selector:
    app: mongo-app
  
